name: imp-universal-bot-release

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file: .env.release
    volumes:
      - ./data/release_db:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ${DOCKER_NETWORK_NAME}

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env.release
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ${DOCKER_NETWORK_NAME}

networks:
  ${DOCKER_NETWORK_NAME}:
    name: ${DOCKER_NETWORK_NAME}
    external: true
