name: verse-bot-main

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file: .env.main
    volumes:
      - ./data/main_db:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env.main
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ~/projects/caddy-static/content/imp:/srv/content/imp
