name: Deploy Release

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: REPO_NAME
          script: |
            if [ ! -d ~/projects/$REPO_NAME ]; then
              mkdir -p ~/projects
              git clone git@github.com:${{ github.repository }}.git ~/projects/$REPO_NAME
            fi
            cd ~/projects/$REPO_NAME

            mkdir -p ./data/release_db

            echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env.release
            echo "TELEGRAM_BOT_USERNAME=${{ secrets.TELEGRAM_BOT_USERNAME }}" >> .env.release
            echo "TELEGRAM_ADMIN_ID=${{ secrets.TELEGRAM_ADMIN_ID }}" >> .env.release
            echo "VK_GROUP_TOKEN=${{ secrets.VK_GROUP_TOKEN }}" >> .env.release
            echo "VK_GROUP_ID=${{ secrets.VK_GROUP_ID }}" >> .env.release
            echo "VK_ADMIN_ID=${{ secrets.VK_ADMIN_ID }}" >> .env.release
            echo "PUBLIC_URL=${{ secrets.PUBLIC_URL }}" >> .env.release
            echo "CADDY_INTEGRATION_PATH=${{ secrets.CADDY_INTEGRATION_PATH }}" >> .env.release
            echo "DOCKER_NETWORK_NAME=${{ secrets.DOCKER_NETWORK_NAME }}" >> .env.release
            echo "POSTGRES_DB=postgres" >> .env.release
            echo "POSTGRES_USER=postgres" >> .env.release
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.release
            echo "POSTGRES_HOST=db" >> .env.release

            git pull origin release
            npm run docker:release:up
