name: Deploy Caddy

on:
  push:
    branches:
      - main
      - release
    paths:
      - 'Caddyfile'
      - 'docker-compose.caddy.yml'

jobs:
  deploy-caddy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Caddy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            CADDY_PATH=~/projects/caddy-static
            mkdir -p $CADDY_PATH

            wget -q -O $CADDY_PATH/Caddyfile https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/Caddyfile
            wget -q -O $CADDY_PATH/docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/docker-compose.caddy.yml

            cd $CADDY_PATH
            docker compose up -d --force-recreate
